speedandfunction/website

- .dockerignore
- Dockerfile
- website/package.json
- Update to Node 23 Alpine for reduced vulnerabilities
- Add non-root user for improved security
- Optimize dependency caching and installation
- Implement health check for container monitoring
- Create .dockerignore to exclude unnecessary files
- Use production-only dependencies to reduce attack surface
> Implement secure Docker setup for Apostrophe CMS

- website/lib/buttonAlignment.js
- website/lib/buttonAlignment.test.js
- website/lib/buttonConfig.js
- website/lib/linkSchema.js
- website/modules/asset/ui/src/scss/_buttons.scss
- website/modules/asset/ui/src/scss/_mixins.scss
- website/modules/buttons-widget/index.js
- website/modules/buttons-widget/views/widget.html
- Refactor button widget to support single and two-button layouts
- Add per-button alignment configuration for single button mode
- Improve button styling with responsive design for mobile and desktop
- Add helpful descriptions for button configuration options
- Implement consistent button spacing and alignment
This update improves the button widget's flexibility and user experience by supporting both single and dual button layouts with proper responsive behavior and clearer configuration options.
> [516] Upgrade Buttons widget

- website/modules/@apostrophecms/form/index.js
move helper functions to methods block
> [553] fix @apostrophecms-form module

- .gitmodules
- Add website-pages submodule to the project
- Configure submodule with correct repository URL
- Link to speedandfunction/website-pages.git repository
This PR adds the website-pages submodule which will store and manage content for the website.
> feat: Add website-pages submodule for content management

- website/modules/asset/ui/src/scss/_buttons.scss
- website/modules/asset/ui/src/scss/_cases.scss
- website/modules/asset/ui/src/scss/_mixins.scss
- website/modules/asset/ui/src/scss/_variables.scss
- website/modules/case-studies-page/views/index.html
- website/modules/case-studies-page/views/show.html
- website/modules/case-studies/index.js
- Add caseStudyType and industry fields to case studies schema
- Update index and show templates to display new field values
- Add help text for better field descriptions in admin UI
This feature enhances the case studies by adding type and industry classifications, improving filtering capabilities and providing more context to visitors.
> [581] Create Case Study Type and Industry entities in Admin UI

- website/views/fragments/fragments.html
> Fix missing endfragment tag in fragments.html

- .github/workflows/deploy_to_railway.yml
- docs/Playwright.md
This PR fixes the spelling and syntax issues in environment selection conditions in workflow files.
> Fix environment selection in workflows

- docker-compose.yml
- scripts/merged-prs-last-24h.js
- website/.eslintrc.js
- website/app.js
- website/app.test.js
- website/e2e/tests/screenshot-test.spec.js
- website/modules/@apostrophecms/express/index.js
- website/modules/@apostrophecms/form/index.js
- website/modules/@apostrophecms/uploadfs/index.js
- website/modules/asset/index.js
- website/modules/map-widget/views/widget.html
- website/utils/env.js
- website/utils/env.test.js
- Refactored AWS S3 configuration in uploadfs module
- Created utility functions for environment variable handling
- Added tests for environment variable utilities
- Updated Docker configuration for consistent environment handling
- Fixed map widget HTML template
- Adjusted express and form module configurations
This PR simplifies and standardizes how environment variables are managed across the application, particularly for AWS S3 storage configuration, making the system more maintainable and secure.
> Fix AWS S3 Configuration and Environment Variables

- website/modules/asset/ui/src/scss/_services.scss
Fixed a bug with no borders for last cards
Added line-height: 110% for title
Added margin-top for description instead of margin-bottom for title
> [593] Fixed bug with no border for last cards

- website/modules/@apostrophecms/form-textarea-field-widget/views/widget.html
- website/modules/asset/ui/src/index.scss
- website/modules/asset/ui/src/scss/_checkbox.scss
- website/modules/asset/ui/src/scss/_form.scss
- website/public/images/check_mark.svg
- Add new checkbox styles in separate SCSS file
- Update form styles for better user experience
- Add SVG check mark icon for checkboxes
- Implement responsive design for forms
- Extract checkbox styles to improve code organization
> [549] style: Update form and checkbox styling for better UX

- .github/workflows/deploy_to_aws.yml
- Add GitHub Actions workflow for AWS deployment automation
- Configure Terraform planning and execution for infrastructure deployment
- Set up environment-specific deployment with Development, Production, and Staging support
- Add workflow dispatch for manual deployment triggers with environment selection
- Include plan-only option for infrastructure review before deployment
- Configure AWS credentials and S3 bucket integration for Terraform state management
- Add comprehensive commented sections for future deployment steps including React app build, Docker image builds, database operations, and service updates
This workflow establishes the foundation for automated AWS infrastructure deployment using Terraform, enabling consistent and reliable deployments across different environments …
> ci: Add AWS deployment workflow with Terraform automation

- website/modules/asset/ui/src/scss/_cases.scss
- website/modules/case-studies-page/views/show.html
- website/modules/case-studies/index.js
- added a new field for a URL in the Admin panel for the Case Study entity
- displayed the "Read the full story" CTA button only if the URL is present
> [617] Make Read the full story button conditional

- website/modules/case-studies/index.js
- website/modules/cases-tags/index.js
Fixed error message in terminal about categories
> [636] Fixed error message in terminal about categories

- Dockerfile
Updated wget package version to 1.25.0-r1
> [643] Update wget package version in dockerfile

- docker-compose.yml
- website/modules/@apostrophecms/form/index.js
- website/modules/@apostrophecms/form/lib/GoogleSheetsFormSubmissionHandler.js
- website/modules/@apostrophecms/form/lib/GoogleSheetsFormSubmissionHandler.test.js
- website/modules/@apostrophecms/form/lib/getSheetsAuthConfig.js
- website/modules/@apostrophecms/form/lib/getSheetsAuthConfig.test.js
- Simplified Google Sheets authentication flow
- Improved form module structure
- Enhanced test coverage
- Implemented Google Sheets service for form submissions
> [669] refactor(form): Improve form module and Google Sheets integration

- website/modules/asset/ui/src/scss/_cases.scss
- fixed an issue in Safari browser where an unexpected extra bottom line appears in the Categories sidebar
> [671] Safari bug: unexpected extra bottom line for Categories in sidebar

- .github/workflows/destroy_aws_environment.yml
- Add FilterHandler class for managing filter navigation and scrolling behavior
- Create enhanceBarbaWithFilterHandling module to coordinate filter functionality
- Add initCaseStudiesFilterHandler for detecting and tracking filter link clicks
- Implement smooth scrolling to filter section when using tag navigation
- Add fade-in animations for case study cards and filter elements
- Create filter anchor point with proper scroll offset for navigation headers
- Update all filter links to include #filter hash for consistent navigation
- Add hover effects and transitions to filter tags for better UX
- Implement accessibility support with reduced motion preferences
- Integrate filter handling with Barba page transitions to prevent unnecessary rerenders
This feature enhancement eliminates page …
> ci: Fix environment parameterization and formatting in destroy AWS workflow

- website/jest.config.cjs
- website/modules/asset/ui/src/scss/_cases.scss
- website/modules/case-studies-page/views/index.html
- website/modules/case-studies/index.js
- website/public/js/modules/case-studies-page/infinite-scroll.js
- website/public/js/modules/case-studies-page/infinite-scroll.test.js
- Implemented infinite scroll loading for case studies
> [560] feat(case-studies): implement infinite scroll

- website/modules/asset/ui/src/scss/_cases.scss
- updated styles for modal corners
> [682] Bug fix: update corners for Filter's modal

- website/modules/@apostrophecms/form-checkboxes-field-widget/views/widget.html
- create form-checkboxes-field-widget
> [679-2] create form-checkboxes-field-widget

- website/modules/cases-tags/index.js
> [663] Sorted tag titles by abc

- website/modules/asset/ui/src/index.js
- website/modules/asset/ui/src/scss/_cases.scss
- website/modules/case-studies-page/views/index.html
- Update close button selector in FilterModal initialization
- Refactor filter modal close button markup and class names in HTML and SCSS
- Adjust filter modal padding and sticky button wrapper styles
> [706] fix: update close button for filter modal on case studies page

- website/modules/asset/ui/src/scss/_header.scss
- website/views/fragments/fragments.html
- Move nav markup inside header div in fragments.html
- Fix css styles for .sf-nav
> [639] fix(header): expanded menu navigation position for desktop

- website/modules/asset/ui/src/scss/_cases.scss
Fixes issue where project titles in case study details cards were not displaying fully. Updated styles to ensure proper text wrapping and visibility.
> [727] Project title does not display fully

- website/.eslintrc.js
- website/app.js
- website/modules/@apostrophecms/global/index.js
- website/modules/@apostrophecms/seo/index.js
- website/modules/@apostrophecms/seo/views/metaHead.html
- website/modules/@apostrophecms/seo/views/tagManagerBody.html
- website/modules/@apostrophecms/seo/views/tagManagerHead.html
- website/package-lock.json
- website/package.json
The PR is connected with the task https://www.goodday.work/t/nYCRcc
__________
1. Paste this code as high in the <head> of the page as possible:
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NVGHJ4PV');</script>
2. Paste this code immediately after the opening <body> tag:
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NVGHJ4PV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
__________
To have the ability to set another GTM_ID, it was added as a …
> GTM implementation.

- .github/workflows/deploy_to_railway.yml
Set up automatic deployment from the release branches with the name pattern 'release/pr-v*'.
> Fix branch rule for automatica production deployment.
