speedandfunction/website

.github/workflows/code-quality.yml, Dockerfile, README.md, docker-compose.override.yml, docker-compose.yml, website/app.js, website/modules/default-page/index.js, website/modules/home-page/index.js, website/package-lock.json, website/package.json
- Create Docker Compose with MongoDB, Redis, and Mongo Express
- Add development environment with hot-reload support
- Implement secure Dockerfile with non-root user
- Configure persistent storage for database and cache
- Add health checks for all services
- Include comprehensive documentation
=> Create complete Apostrophe CMS Docker environment

.github/workflows/code-quality.yml
Added a permissions block to the code-quality.yml workflow that limits the workflow's access to only what it needs:
- Read access to repository contents
- Write access to security events for scan results
This follows the principle of least privilege and improves overall security.
=> Explicit permissions to GitHub workflow

scripts/import_mongodb.sh
- Add detection for local MongoDB connections using localhost or 0.0.0.0
- Use docker exec for local connections rather than creating new containers
- Improve command-line argument parsing with a for loop
- Standardize mongoimport command usage via stdin redirection
- Fix parameter handling when flags are passed first
These changes improve the import script's functionality when working with local MongoDB instances in Docker containers, reducing overhead and making the script more flexible.
=> Improve MongoDB import script for local connections

.github/CODEOWNERS
This PR adds a CODEOWNERS file to automatically assign @killev as the default reviewer for all pull requests.
=> Add CODEOWNERS file to set default code reviewer

website/modules/asset/ui/src/scss/_base.scss, website/views/fragments/fragments.html, website/views/layout.html
- Implement breadcrumbs component in fragments.html
- Add accessibility attributes for better screen reader support
- Create navigation structure with proper hierarchy
- Add special styling for current page indicators
- Connect breadcrumbs with page ancestry data
- Integrate breadcrumb fragment into layout template
=> [537] Add breadcrumbs implementation

docker-compose.override.yml, docker-compose.yml, init-localstack.sh, website/app.js, website/app.test.js, website/modules/@apostrophecms/uploadfs/index.js
- Use gresau/localstack-persist image for persistent S3 data
- Add init-localstack.sh script for automatic bucket setup
- Configure S3 endpoint properly with path style access
- Add URL hook to replace 'localstack' with 'localhost' in attachment URLs
- Improve uploadfs module with better default configuration
- Add comprehensive tests for attachment URL hook functionality
=> fix: Improve S3 URLs for localhost development environment

website/modules/asset/ui/src/scss/_base.scss, website/modules/asset/ui/src/scss/_header.scss, website/modules/asset/ui/src/scss/_layout.scss, website/views/layout.html
- Fix breadcrumb container width and positioning
- Add proper padding instead of margins for breadcrumb nav
- Move breadcrumbs inside main content area
- Adjust spacing for main content area
- Fix header logo font settings
=> [596] fix: Breadcrumb margins and rendering issues

website/modules/asset/ui/src/scss/_page-intro.scss, website/modules/page-intro-widget/index.js, website/modules/page-intro-widget/views/widget.html
- Change 'description' to 'descriptions' array in widget schema
- Update widget.html to render multiple descriptions
- Adjust SCSS for new layout and spacing
This PR updates the page intro widget to support multiple description blocks, improving flexibility for content editors.
=> [609] feat(page-intro-widget): Support multiple description blocks

website/modules/asset/ui/src/scss/_base.scss, website/views/fragments/fragments.html
fix: update breadcrumbs styles and logic
- Adjust breadcrumbs margin and responsive spacing in SCSS
- Remove .breadcrumb-home style and related HTML logic
- Simplify breadcrumbs fragment logic for home page
These changes improve the visual consistency and maintainability of the breadcrumbs component.
=> [610] fix: update breadcrumbs styles and logic

website/modules/asset/ui/src/scss/_page-intro.scss
- Remove unnecessary margins from title, subtitle, and description - Set max-width for title, subtitle, and description individually - Adjust spacing for better alignment on all breakpoints
=> [623] Fix alignment and spacing in page intro widget

.cursor/tmp/commit-msg.txt, website/modules/@apostrophecms/home-page/index.js, website/modules/@apostrophecms/page-type/index.js, website/modules/case-studies-page/index.js, website/modules/default-page/index.js
- Add global page-type module to remove orphan field
- Remove orphan field from home-page module
- Remove orphan field from case-studies-page module
- Remove orphan field from default-page module
This removes the 'hide in navigation' option (orphan field) from all page types to streamline the content management interface and eliminate unused functionality.
=> [658] feat: Remove orphan field from page types

website/modules/team-members/index.js
- Remove order field from sort configuration
- Remove order field schema definition with label, help text, and validation
- Remove order field from basics group field list
- Remove order field from columns configuration
This change simplifies the team members module by removing manual ordering functionality, allowing the team to be sorted by title and update time instead of requiring manual order management.
=> [662] refactor: Remove order field from team members configuration

.cursor/tmp/commit-msg.txt, .github/workflows/destroy_aws_environment.yml
- Add GitHub workflow for destroying AWS environments
- Include manual workflow dispatch with environment selection
- Add plan-only option to preview destruction without executing
- Implement three-stage process: destroy-plan, manual-approval, destroy-apply
- Add proper permissions for issue writing
- Include placeholder steps for future implementation
This workflow is necessary to provide a safe and controlled way to destroy AWS environments when they are no longer needed, helping to reduce infrastructure costs and maintain clean environments.
=> feat(ci): Add destroy AWS environment workflow

website/modules/@apostrophecms/form/index.js
Hid unused elements in form, leaving only:
- text input
- text area input
- checkbox input
- rich text
=> [677] Hid unused elements in form

website/modules/asset/ui/src/scss/_buttons.scss
- fix letter-spacing for button;
- remove min-width and max-width for button
=> fix buttons responsive spacing

website/modules/asset/ui/src/scss/_table-widget.scss, website/modules/table-widget/index.js, website/modules/table-widget/views/widget.html
- updated table widget with improved styling and functionality
=> [715] Correct links should be added to Learn more

website/modules/asset/ui/src/scss/_buttons.scss
- fix button padding;
- fix button border
=> [696] fix/button padding border

website/modules/asset/ui/src/scss/_cases.scss, website/modules/case-studies-page/views/index.html
Key fixes include:
🧭 Tag count alignment: Tag count now appears immediately after the tag label (no awkward spacing).
📐 Spacing adjustments: Replaced margin: 0 -8px with margin-left: -8px to avoid unintended right-side offset.
✂️ Truncation fix: Removed invalid @include truncate-lines(1) from .remove-tag which doesn’t apply to inline-flex elements.
=> [704] align tag count and improve truncation behavior

website/modules/asset/ui/src/scss/_services.scss
Fixed styles for Simple Cards widget to display the data according to design
=> [699] Fixed styles for Simple Cards widget

website/modules/testimonials-carousel-widget/views/widget.html, website/modules/testimonials/index.js, website/views/fragments/utilities.html
Changes:
- Updated feedback field help text in testimonials/index.js
- Left the raw string untouched in the database, but presentation now wraps quotes in template
- Adjusted frontend template to include opening and closing quotation marks
=> [694] auto-wrap feedback with quotes and update help text

website/modules/@apostrophecms/form-widget/index.js, website/modules/@apostrophecms/form-widget/views/widget.html, website/modules/asset/ui/src/js/formValidation.js, website/modules/asset/ui/src/js/formValidation.test.js, website/modules/asset/ui/src/scss/_form.scss
- Refactor form widget HTML to use native form attributes and remove custom data attributes
- Overhaul form validation JS: async validation, server-side error handling, disables submit during submission
- Add tests for submit button disabling and multiple submit prevention
- Update form SCSS for input height and responsive styles
=> [679-4] feat(form):enhance validation UX and prevent duplicate submissions

website/modules/asset/ui/src/scss/_leadership-team.scss
This pull request addresses the issue where a scrollbar briefly appears when text loads and then disappears.
=> [714] Scrollbar appears briefly when the text loads and then disappears

website/modules/leadership-team-widget/views/widget.html, website/modules/team-members/index.js
Changes:
- Rename "Experience" title to "Joined in" in Admin UI
- Rename help text from "Experience in years" to "Enter the year"
- Replace "[year]" with "Joined in [year]" for team members cards
=> [755] update team member experience field

website/app.js, website/modules/@apostrophecms/form-widget/views/widget.html
- Add CSRF token to form widget template
- Add CORS configuration for production environment
=> [785] fix: resolve 403 Forbidden error on form submission in production

website/app.js, website/e2e/tests/screenshot-test.spec.js
See conversation
https://spdfn.slack.com/archives/C2EKL870Q/p1755529615932599
We may lose BASE_URL inside the replacer endpoints.
The only way to check is to try that fix.
=> Quick fix: production URL if there is no in env.

website/modules/asset/ui/src/clientSideFiltering.js, website/modules/asset/ui/src/scss/_cases.scss, website/modules/case-studies-page/views/index.html
Made the list opened if tag is selected
=> Made the list opened if tag is selected

website/modules/@apostrophecms/global/index.js, website/modules/asset/ui/src/scss/_footer.scss, website/views/fragments/fragments.html
- replaced comAddress field with companyMission and reorganized footer field structure
- updated SCSS classes from sf-footer__top to sf-footer__mission and improved responsive behavior
- converted hardcoded footer content to dynamic rendering using global module data
=> [604] Refactor footer to use dynamic CMS content
